### ISSUE TITLE
Decide which CharacteristicNames to highlight

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#2]
We'll need to decide which `CharacteristicName`'s to target for our WQP pull and clean pipeline. I think the trends and drivers effort is focused on nutrients, salinity, and 1-2 other major groups. Perhaps we should try to choose a few examples from that list.

**Comment by padilla410** [comment]
I just completed a review of the [`nawqa_wqp` repo](https://github.com/USGS-R/nawqa_wqp). We could nab characteristic codes directly out of [this](https://github.com/USGS-R/nawqa_wqp/blob/main/1_wqpdata/cfg/wqp_codes.yml) configuration file.
