### ISSUE TITLE
Which siteTypes should we query?

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#20]
Which `siteTypes` (and `sampleMedia`) within WQP should we target for this pipeline? For simplicity, I'll propose the following criteria which we can always expand on later:

```
siteType = "Stream"
sampleMedia = c("Water", "water")
```

However, we could also widen the search off the bat to include other surface waters (or even groundwater). In [2wp-temp-observations](https://github.com/USGS-R/2wp-temp-observations/blob/174875b69c335436bf5acdeee8a53e5334ac72de/1_wqp_pull/cfg/wqp_pull_params.yml), the `sampleMedia` is as above but `siteType` includes `c("Lake, Reservoir, Impoundment", "Stream", "Wetland")`.

**Comment by lindsayplatt** [comment]
I think `siteType` is very project specific, so I like the idea of limiting. I think it would be nicer to have a working example that is robust to scaling, but doesn't actually take the length of a national pull as written. I think documentation of options and where you go to find the list of potential `siteType`s (and any other pull parameter) is the more critical piece.
