### ISSUE TITLE
Add 1_fetch/out/.placeholder

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-example-wqp#34]
I would suggest committing an empty text file for any folder that the pipeline needs to run ([as this example does](https://github.com/USGS-VIZLAB/forecast-drb/tree/main/1_fetch/out)). Otherwise, users get somewhat mysterious failures when I try to build `tar_make(p1_similar_char_names_txt)`.

**Comment by lekoenig** [comment]
Ah, OK! So cloning the repo which doesn't contain a `1_fetch/out/` directory is what's causing these failures?

**Comment by lindsayplatt** [comment]
Yes, exactly! This can be handled by either 1) committing a placeholder as suggested here, or 2) adding an `if(!dir.exists(dir)) dir.create(dir)` but I personally think that 1 is cleaner.

This throws an error because the directory is not yet created 
```r
# tar_dir() runs this reproducible pipeline in a tmp directory
tar_dir({
  tar_script({
    tar_option_set()
    list(
      tar_target(
        testfile, {
          fn <- 'out/helloworld.txt'
          writeLines('hello, world', fn)
          return(fn)
        }, format='file')
    )
  }, ask=FALSE)
  tar_make()
})
```

![image](https://user-images.githubusercontent.com/13220910/169045328-fbafa79d-5136-4439-a2b5-340584c877a5.png)


This pipeline runs fine because the directory is created first
```r
tar_dir({
  dir.create('out') # DIRECTORY CREATED
  tar_script({
    tar_option_set()
    list(
      tar_target(
        testfile, {
          fn <- 'out/helloworld.txt'
          writeLines('hello, world', fn)
          return(fn)
        }, format='file')
    )
  }, ask=FALSE)
  tar_make()
})
```

![image](https://user-images.githubusercontent.com/13220910/169044847-1384897b-e861-45b9-883d-aca144e97ad3.png)
