### ISSUE TITLE
Error when re-building p1_wqp_inventory

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#39]
Both @jread-usgs and I have noticed an odd error that shows up _after_ the pipeline is built successfully but then a parameter like `end_date` gets changed:

![error](https://user-images.githubusercontent.com/8785034/170365860-d3924558-b5f9-41e9-9fbe-58cb81bb45d8.png)

Re-building the pipeline then requires changing a parameter like `dist_m` to invalidate `p1_conus_grid_aoi`. Why do we need to do this?

**Comment by jsadler2** [comment]
As you know, @lekoenig, we've run into this in the DO project. And I was just running into it again in what I think was a case sort of independent of targets. I was trying to do a filter on an sf object that I had read in using `targets::tar_read` and I was getting this error. 

At first I thought it was a targets thing so I did `tar_invalidate` and then `tar_make` and then `tar_read` again - same error.

That made me think it wasn't a targets thing but an SF thing. So I googled the error and it took me here: https://github.com/r-spatial/sf/issues/1381#issuecomment-802861197

Based on that comment I did a `library(sf)` call and then my filter worked without any problem! So maybe making that call is a workaround.

**Comment by lekoenig** [comment]
Thanks, @jsadler2! I came across this yesterday, but thought the {sf} import would be properly handled in `tar_option_set` when we define our packages. Inspired by your success, I just tried to add the following lines _above_ the code chunk that declares the function `inventory_wqp()` in `1_fetch/src/get_wqp_inventory.R` and lo and behold, the pipeline builds! 🎉 

```
#' explicitly import sf package to handle geometry data in `grid`
library(sf)
```

This is probably a suitable workaround to make sure our pipeline rebuilds when needed, although we may still want to consider deferring to representing the grids as bbox's within a tibble to avoid brittle issues with {sf}.

**Comment by padilla410** [comment]
Troubleshooting my own bug in `lake-temperature-model-prep` and end up here 👋
