### ISSUE TITLE
Simplify p1_conus_grid by omitting CONUS and tigris dependencies

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#42]
_From #41:_ 
> One limitation of the current pipeline is the reliance on a CONUS boundary to set up the cells for inventory. I think you may want to consider modifying this for two reasons: 1) the [CONUS boundaries](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/blob/2e8487f370c2e16252b58f7a23b49d90f2249540/1_fetch/src/create_grids.R#L24) will exclude use of the pipeline in AK, HI, PR and other places whttps://github.com/USGS-R/dataRetrieval/issues/616 WQP data exists, such as Guam, 2) the edge of the CONUS map is a little arbitrary and results in cells that aren't referenced from an integer (which can cause another odd issue as documented here ) and the grid cells look like this:
> 
```
> sf::st_bbox(p1_conus_grid[1,1])
>       xmin       ymin       xmax       ymax 
> -124.84897   24.39631 -123.84897   25.39631 
```
> and small updates or different years of the tigris::states year could nudge this in a small way and invalidate the inventory even if the change isn't helpful to the WQP inventory itself.

Instead, @jread-usgs posed a great suggestion that we could just use the `offset` argument within `sf::st_make_grid()`. This approach has the benefit of being more inclusive of areas outside of CONUS where WQP data exists, and also isn't subject to small differences in the shapefiles from {tigris} that could invalidate the inventory unnecessarily.

**Comment by lekoenig** [comment]
I don't think this would be a problem for our workflows, but I'll note that the `offset` argument specifies the lower-left extent of the grids. So the grids would expand down and to the left as a user adjusts the integers in `offset`, e.g.:

```
> tar_load(p1_AOI_sf)
> # Define big grid (currently `p1_conus_grid`):
> big_grid <- sf::st_make_grid(p1_AOI_sf, offset = c(-124.84897, 24.39631), crs=4326, cellsize = cellsize)
> mapview(big_grid) + mapview(p1_AOI_sf, col.region = "darkorange")
```
![big_grid](https://user-images.githubusercontent.com/8785034/171279891-65a1dafd-34a7-4e5c-a260-0c0b3a2bbe22.png)

**Comment by jread-usgs** [comment]
@lekoenig I'm thinking the actual offset would be either within the grid function itself (e.g., hidden from the user and always something like -180, -90) or an arg that is possible to set in the function but has a default and isn't shown in the example pipeline. 

But perhaps I'm thinking about this in a different way - I'm thinking that having a grid that covers the globe and quickly filtering that to the overlap of the AOI is relatively cheap.

**Comment by lekoenig** [comment]
@jread-usgs Ah, OK. The example below doesn't use `offset` but I think we could incorporate a default offset like this, especially if the returned cell size doesn't need to always match the target `cellsize`:

```
# moar grids!
> all_the_grids <- sf::st_make_grid(
+     st_bbox(c(xmin = -180,
+               xmax = 180,
+               ymax = 90,
+               ymin = -90), crs = st_crs(4326)), what = "polygons", square = TRUE, cellsize = c(2,2))
> mapview(all_the_grids)
```
![all_the_grids](https://user-images.githubusercontent.com/8785034/171290002-76341f4f-f3c9-494c-a153-306b321e0116.png)

**Comment by jread-usgs** [comment]
Yes, that would definitely work as well for keeping the cells the same for various builds in the same pipeline when the AOI can move around or expand.

**Comment by lindsayplatt** [comment]
@lekoenig I think I solved these issues in my national chlorophyll version of this pipeline! Let's talk about integrating these approaches
