### ISSUE TITLE
Rename target phases for this pipeline?

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#61]
I originally set up this targets pipeline to have two phases, 1_fetch and 2_process. I think these steps still represent the primary divisions of the workflow, to pull and (lightly) clean data. However, I'm wondering if alternate names would be more intuitive for a broader audience. Some proposed options:

1.  Leave target phase names as  they are
2. 1_inventory, 2_download, 3_process 
3. 1_inventory, 2_download, 3_harmonize

I'm leaning towards 3 because I think these phase names seem to align with the vocabulary used in IWAAs projects. What do you think, @padilla410, @lindsayplatt?

**Comment by lindsayplatt** [comment]
I also like 3! And I think "harmonize" better characterizes the goal with that stop. We aren't doing major processing, just some lightweight steps to be able to use the data in future processing.
