### ISSUE TITLE
Flip wqp inventory and data pull comparisons back

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-example-wqp#70]
When running the code for reviewing #69, I got a message about the inventory and the data having different numbers of records. This seemed odd because both had just built within the same 10 minute span. I dug into the `summarize_wqp_data()` function and found that [the `records` and `sites` for what was downloaded and what was inventoried](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/blob/main/1_inventory/src/summarize_wqp_records.R#L70-L71) were [recently switched by accident](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/commit/1c345d1a56fc48820df2fe162af851b3be482f5c#diff-dc9e18c6a2fc879cf1d989cadca72ee04358dccbffb43d3fb3ee3e8cfe12be69L57-R71). So, we are comparing the excpected number of records to the downloaded number of sites and vice versa. 

A simple flip of these two object names will solve the problem!

```r
compare_summaries <- wqp_summary %>%
    left_join(wqp_inventory_summary, by = "CharacteristicName") %>% 
    mutate(results_diff = n_records_expected - n_records,
           sites_diff = n_sites_expected - n_sites)
```

**Comment by lekoenig** [comment]
lol it was me 😱
