### ISSUE TITLE
Add assert statement for dataRetrieval package version

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#82]
@jordansread discovered that older versions of `dataRetrieval` will throw somewhat cryptic errors if a user runs our pipeline using `tar_make()`. The specific error is `Error: arguments imply differing number of rows: 1, 0` and the inventory is empty. Jordan also did some testing and thinks that the package version needs to be at least `2.7.6.9003` to avoid this issue. 

We should inform the user about this dependency. One way is to add a step that checks the package version and stops the inventory step if the package version is too old, something like `stopifnot(packageVersion >= something)`.

**Comment by jordansread** [comment]
I guess this is a bit simpler then I remember it being, since `packageVersion` doesn't return a character and is a special version number
```r
class(packageVersion('dataRetrieval'))
[1] "package_version" "numeric_version"
```

So you could error when this case is met
```r
(packageVersion('dataRetrieval') < "2.7.6.9003")
```
