### ISSUE TITLE
Unexpected `p2_wqp_data_aoi` rebuilds due to attributes

### ISSUE THREAD

**Issue by padilla410** [USGS-R/ds-pipelines-targets-example-wqp#87]
I am seeing unexpected rebuilds when I run `tar_make` two times in a row. This seems to be due to attributes associated with WQP data.

The general pattern for reproducing this error is as follows:
1. Run `tar_make()`
2. Store a few branches in dummy variable names
3. Run `tar_make()` again and compare using `all.equal`

Initial run:
```r
tar_make()
tar_load(c(p2_wqp_data_aoi_ed531b3e, p2_wqp_data_aoi_16647180))

# you may need to select different branches
x_1 <- p2_wqp_data_aoi_ed531b3e
x_2 <- p2_wqp_data_aoi_16647180
```

Second run:
```r
tar_make()
tar_load(c(p2_wqp_data_aoi_ed531b3e, p2_wqp_data_aoi_16647180))
```

Compare
```r
all.equal(x_1, p2_wqp_data_aoi_ed531b3e)

all.equal(x_2, p2_wqp_data_aoi_16647180)
```

Results:
```r
> all.equal(x_1, p2_wqp_data_aoi_ed531b3e)
[1] "Attributes: < Component “queryTime”: Mean absolute difference: 263.6266 >"

> all.equal(x_2, p2_wqp_data_aoi_16647180)
[1] "Attributes: < Component “queryTime”: Mean absolute difference: 266.7494 >"
```

When experimenting with this, I have also seen mismatches in other attribute parameters, such as this:
```r
> all.equal(p2_wqp_data_aoi_7137bdea, x_1)
[1] "Attributes: < Component “headerInfo”: Component “date”: 1 string mismatch >"       
[2] "Attributes: < Component “headerInfo”: Component “via”: 1 string mismatch >"        
[3] "Attributes: < Component “headerInfo”: Component “x-amz-cf-id”: 1 string mismatch >"
[4] "Attributes: < Component “queryTime”: Mean absolute difference: 144.6471 >" 
```

**Comment by lekoenig** [comment]
Thanks for documenting this, @padilla410! So to confirm, when you run `tar_make()` a second time, branches are being rebuilt even if there were no changes to upstream dependencies? 

I have not been able to reproduce this behavior on my local clone. First, do you mind updating your fork using `git pull upstream main` to make sure that this issue is unique and not addressed by older fixes (e.g. I'm thinking of [this](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/issues/63) issue, where I noticed unexpected builds in `p2_wqp_data_aoi`)? 

Regardless, I've been aware of the attributes that get appended by `readWQPdata()` and have wondered if they would cause issues. We may want to omit these attributes to make unnecessarily rebuilds less likely, but also because I'm not sure the information like query time is still useful when the different branches are combined in `p2_wqp_data_aoi`.

**Comment by padilla410** [comment]
I don't have any firm solutions yet, but I am documenting a little more sleuthing on my end. First, I confirmed that I had the most up-to-date version of `main` (as requested above). Then I ran the pipeline twice.

Here is what I am seeing on the second rebuild: 
![image](https://user-images.githubusercontent.com/15007294/182938847-0d37c6f6-9585-4406-bcb9-251242b9bb21.png)

Notice where the rebuilds start: `p2_wqp_data_aoi_3387cb9d`. I re-ran `tar_make` a few times and the process continually kicked off downstream rebuilds at this point. I do not have an explanation for the cryptic `eval(expr = expr, envir = envir)`. When I ran this pipeline I set `workspace_on_error = TRUE` and then loaded the workspace for that branch using `tar_workspace(p2_wqp_data_aoi_3387cb9d)` and the debugger on `fetch_wqp_data`. I was able to successfully step through all parts of `fetch_wqp_data` without a problem. `p2_wqp_data_aoi_3387cb9d` returns zero records, but so do many of my targets. Here is a screenshot of my environment after running `tar_load(starts_with('p2_wqp_data_aoi_'))`:
![image](https://user-images.githubusercontent.com/15007294/182948133-63636aef-914f-4bfc-ae45-6000e912e579.png)

**Comment by lekoenig** [comment]
Huh, this is pretty strange. The attributes get appended when building `p2_wqp_data_aoi` so I don't understand why those would actually _trigger_ a rebuild of branches like `p2_wqp_data_aoi_3387cb9d`. Is `p2_site_counts_grouped` being rebuilt too, or just these wqp data branches?

**Comment by lekoenig** [comment]
Thanks for your patience, @padilla410, I haven't forgotten about this 🙂. Lindsay and I just merged a PR that should get rid of the need for empty data calls. Whenever you get a chance, I'd be curious if you still see these unexpected rebuilds with the latest code.

**Comment by padilla410** [comment]
Resolved! I have not been able to reproduce the original error. To test I pulled down the latest version of the repo, built it and then built it again. All targets were skipped on the second build.
