### ISSUE TITLE
Consider keeping resultCount to be specific to the group of CharNames

### ISSUE THREAD

**Issue by jordansread** [USGS-R/ds-pipelines-targets-example-wqp#88]
I may not be understanding exactly how this works, but I'm going to give it a try:

I think [p1_wqp_inventory_aoi](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/blob/059bf02fec97b9ab7de778475ae3d26d0b7162f4/1_inventory.R#L102) is the full tibble of all monitoring sites with data that meet the criteria and appropriate additional information that we use, such as `resultCount`. This information is used later to group the data pulls efficiently. 

I see that the data pulls are now branching across grid cell, characteristic name, and resultCount group. I think this is a good approach but didn't realize the charName branching would be across all unique charNames as opposed to an umbrella grouping (like "temperature" or "conductivity" which each have four unique charName) <- _let's ignore this impact but I think it is relevant in the future because of how many unique branches it will create, for example when adding P or N to the mix (which have way more unique names)._ 

Anyhow, these groups are made and then branches are spun off to do the data downloads. There will be one for each unique cell (`grid_id`), lumped sites based on groupings of site-specific sum of `resultCount`, and charName. [Here](https://github.com/USGS-R/ds-pipelines-targets-example-wqp/blob/059bf02fec97b9ab7de778475ae3d26d0b7162f4/2_download.R#L12) each monitoring location's `resultCounts` across all unique CharNames are summed, giving a total `results_count` that is used for lumping sites together for the grid- and char-specific data pulls. 

I think this should be revisited because the result of this summarization is probably making the full data pull take a lot more time than necessary for a couple of reasons: 1) sites that have a lot of data for just one of these CharNames are going to end up as isolated site-data pulls for _all_ CharNames, even if the site has no data for any of the other ones. 2) because the `result_count` used to create `download_grp` is based on the total records for all params, the `add_download_groups()` function call is going to group sites much more conservatively when multiple CharNames (that actually have data behind them, i.e., aren't super rare names) are in play and probably create a number of empty data calls. Both of these issues ultimately result in a lot more branches being created than necessary and a lot more calls to WQP, each with a significant web service call overhead that takes time. 

I ran into this when seeing the following build pattern and also realized that there are _no_ sites in this pull that have data with the "Temperature" or "Temperature, water, deg F" CharName (all of the data is either in "Temperature, sample" or "Temperature, water" for this footprint and param set)
<img width="893" alt="image" src="https://user-images.githubusercontent.com/2349007/182868542-2e52e474-41e8-44b7-abf7-df5d71fb38e6.png">

My proposal would be to keep `resultCount` associated with the level of branching being done and apply that to create download groups at the same branching level. You _could_ choose to lump similar CharNames together (see comment above where I said "..ignore this impact") and summarize `resultCount` with _that_ grouping, but that may lead to unnecessary complexity and I don't think it would save much time in this case. 

Here is an example of this in action - there are 62 unique `download_grp`s in my current pull. I've limited the charNames to just the four temperature ones, but that means we'll make 248 queries to WQP in this case. 124 of those will be empty (as I mentioned above, two of these CharNames don't have any sites for this footprint/param combo). For "Temperature, sample", all of the sites with data are concentrated to 7 grid cells (and 8 download groups, meaning the other 54 queries will be empty):
```r
p1_wqp_inventory_aoi %>% filter(CharacteristicName == 'Temperature, sample') %>% 
    select(site_id = MonitoringLocationIdentifier, resultCount) %>% 
    left_join(p2_site_counts_grouped, by = 'site_id') %>% 
    group_by(download_grp) %>% summarize(result_total = sum(resultCount))
# A tibble: 8 × 2
  download_grp result_total
  <chr>               <dbl>
1 11386_01             2951
2 11565_01              937
3 11566_01             5891
4 11745_01              628
5 11746_01             1530
6 11925_01              130
7 11926_01             1343
8 11926_02              125
```

Most of the data is in 'Temperature, water' and there are data expected for each of the 62 `download_grp`s in this case:
```r
p1_wqp_inventory_aoi %>% filter(CharacteristicName == 'Temperature, water') %>% 
    select(site_id = MonitoringLocationIdentifier, resultCount) %>% 
    left_join(p2_site_counts_grouped, by = 'site_id') %>% 
    group_by(download_grp) %>% summarize(result_total = sum(resultCount))
# A tibble: 62 × 2
   download_grp result_total
   <chr>               <dbl>
 1 11385_01              236
 2 11385_26                1
 3 11385_27                1
 4 11385_28                1
 5 11385_29                1
 6 11385_30                1
 7 11385_33                2
 8 11385_34                1
 9 11385_35                1
10 11386_01             8458
# … with 52 more rows
```

**Comment by lekoenig** [comment]
> Both of these issues ultimately result in a lot more branches being created than necessary and a lot more calls to WQP, each with a significant web service call overhead that takes time.

This issue highlights a trade-off between minimizing unnecessary calls to WQP and discretizing the data pulls to avoid unnecessary rebuilds. We could chunk the data pulls 1) by record counts alone; 2) by each characteristic name; or 3) by groups of characteristic names that are thematically similar (e.g. "temperature"). We started with the first option and the functionality in `add_download_groups()` reflects that choice. The idea to further map the WQP calls across character names was motivated by the fact that we didn't want to have to re-pull all data if, for example, a single characteristic name were changed. I think this is a good idea in theory, but I agree with you assessment above. If we maintained the workflow of mapping over unique characteristic names, it sounds like it'd be more efficient to incorporate that into our group assignments rather than the use of `cross` within the target itself. However, I've also recognized that the number of branches gets potentially unwieldy when the spatial footprint is expanded beyond our small example AOI and/or when many parameters are requested. @jordansread, do you mind sharing the inputs (lat/lon & `wqp_args`) you used to generate this example? I'll experiment a bit with options 2 + 3 and ways to incorporate these branching decisions into `add_download_groups()`.

**Comment by jordansread** [comment]
@lekoenig I used the following:

```r
param_groups_select <- c('temperature')

# Specify coordinates that define the spatial area of interest
# lat/lon are referenced to WGS84
coords_lon <- c(-96.333, -87.8, -89)
coords_lat <- c(42.547, 45.029, 35)

# Specify arguments to WQP queries
# see https://www.waterqualitydata.us/webservices_documentation for more information 
wqp_args <- list(sampleMedia = c("Water","water"),
                 siteType = "Lake, Reservoir, Impoundment",
                 # return sites with at least one data record
                 minresults = 1, 
                 startDateLo = start_date,
                 startDateHi = end_date)
```

**Comment by lekoenig** [comment]
If we sum `resultCount` for each `CharacteristicName` in `p2_site_counts`, we can also modify `add_download_groups()` slightly so that separate task numbers (and eventually, download groups) would get assigned for unique characteristics, which would mimic the behavior we've previously tried to capture using `cross` in `p2_wqp_data_aoi`. 

Here's a reprex with 5 sites spanning two `grid_id`'s:

```r
> sitecounts <- tibble(MonitoringLocationIdentifier = c("A","B","C","D","E"), 
+                      lon = c(rep(-92.4, 5)), 
+                      lat = c(rep(42.5,5)), 
+                      datum = c(rep("WGS84",5)), 
+                      grid_id = c(rep("11923", 4), "11924"), 
+                      CharacteristicName = c(rep("Temperature, water", 3), rep("Temperature", 2)), 
+                      results_count = c(151, 247000, 7500,15000,134))
```

Keeping `add_download_groups()` as is would result in multiple characteristics per task (which are grouped based on reaching a threshold number of records):

```r
> # Current grouping routine
> # from 2_process/src/fetch_wqp_data.R, in add_download_groups() fn
> sitecounts %>%
+     rename(site_id = MonitoringLocationIdentifier) %>% 
+     split(.$grid_id) %>%
+     purrr::map_dfr(.f = function(df){
+         
+         df_grouped <- df %>%
+             arrange(desc(results_count)) %>%
+             mutate(task_num = MESS::cumsumbinning(x = results_count, 
+                                                   threshold = max_results, 
+                                                   maxgroupsize = max_sites))
+     }) %>%
+     mutate(pull_by_id = TRUE) %>%
+     arrange(grid_id, task_num)
# A tibble: 5 x 9
  site_id   lon   lat datum grid_id CharacteristicName results_count task_num pull_by_id
  <chr>   <dbl> <dbl> <chr> <chr>   <chr>                      <dbl>    <int> <lgl>     
1 B       -92.4  42.5 WGS84 11923   Temperature, water        247000        1 TRUE      
2 D       -92.4  42.5 WGS84 11923   Temperature                15000        2 TRUE      
3 C       -92.4  42.5 WGS84 11923   Temperature, water          7500        2 TRUE      
4 A       -92.4  42.5 WGS84 11923   Temperature, water           151        2 TRUE      
5 E       -92.4  42.5 WGS84 11924   Temperature                  134        1 TRUE      
>
```
^Maybe this is OK, but once we start to add different parameter groups, it might be preferable to query different characteristics/parameter groups separately, to avoid unnecessary rebuilds if, say, a single characteristic got updated. If we want to consider characteristic names when we assign download groups, we can use something like the code chunk below instead of forcing `cross` in `p2_wqp_data_aoi`. This would result in 4 queries since we concatenate `grid_id` and `task_num` when creating `download_grp`'s:


```r
> # Proposed change that would result in separate task_numbers for 
> # different characteristics within a grid
> sitecounts %>%
+   rename(site_id = MonitoringLocationIdentifier) %>% 
+   split(.$grid_id) %>%
+   purrr::map_dfr(.f = function(df){
+     
+     df_grouped <- df %>%
+       group_by(CharacteristicName) %>%
+       arrange(desc(results_count)) %>%
+       mutate(task_num_by_results = MESS::cumsumbinning(x = results_count, 
+                                                        threshold = max_results, 
+                                                        maxgroupsize = max_sites), 
+              task_num = task_num_by_results - 1 + cur_group_id()) %>%
+       ungroup()
+   }) %>%
+   mutate(pull_by_id = TRUE) %>%
+   arrange(grid_id, task_num)
# A tibble: 5 x 10
  site_id   lon   lat datum grid_id CharacteristicName results_count task_num_by_results task_num pull_by_id
  <chr>   <dbl> <dbl> <chr> <chr>   <chr>                      <dbl>               <int>    <dbl> <lgl>     
1 D       -92.4  42.5 WGS84 11923   Temperature                15000                   1        1 TRUE      
2 B       -92.4  42.5 WGS84 11923   Temperature, water        247000                   1        2 TRUE      
3 C       -92.4  42.5 WGS84 11923   Temperature, water          7500                   2        3 TRUE      
4 A       -92.4  42.5 WGS84 11923   Temperature, water           151                   2        3 TRUE      
5 E       -92.4  42.5 WGS84 11924   Temperature                  134                   1        1 TRUE      
>
```

These changes would capture the intended behavior in the current pipeline, but would get rid of the empty data calls (yay!). Grouping by records and characteristic names could still result in many branches though, so I am open to grouping by parameter groups instead. This would add a bit more complexity to the pipeline (i.e., using `p1_char_names_crosswalk`) but would reduce the number of branches and might align more closely with the behavior a user might want/expect(?).

**Comment by jordansread** [comment]
I think grouping/summing by charNames (not parameter groups) makes the most sense here and keeps code complexity reduced.

**Comment by lekoenig** [comment]
On second thought, I wonder if my reprex above is actually capturing our use case accurately. For example, what if I added another site that had data with `CharacteristicName == "Temperature"` so that there were 2 `task_num` for that group?

```r
> sitecounts <- tibble(MonitoringLocationIdentifier = c("A","B","C","D","E","F"), 
+                      lon = c(rep(-92.4, 6)), 
+                      lat = c(rep(42.5,6)), 
+                      datum = c(rep("WGS84",6)), 
+                      grid_id = c(rep("11923", 5), "11924"), 
+                      CharacteristicName = c(rep("Temperature, water", 3), rep("Temperature", 3)), 
+                      results_count = c(151, 247000, 7500,15000,235004,134))
> sitecounts
# A tibble: 6 x 7
  MonitoringLocationIdentifier   lon   lat datum grid_id CharacteristicName results_count
  <chr>                        <dbl> <dbl> <chr> <chr>   <chr>                      <dbl>
1 A                            -92.4  42.5 WGS84 11923   Temperature, water           151
2 B                            -92.4  42.5 WGS84 11923   Temperature, water        247000
3 C                            -92.4  42.5 WGS84 11923   Temperature, water          7500
4 D                            -92.4  42.5 WGS84 11923   Temperature                15000
5 E                            -92.4  42.5 WGS84 11923   Temperature               235004
6 F                            -92.4  42.5 WGS84 11924   Temperature                  134
> 
```

We would actually still see a task number of "2" used for two separate characteristic names (i.e., rows 2 and 3 below). Because we concatenate `grid_id` and `task_num` to get `download_grp`, this would not result in unique download groups for the different characteristic names:

```r
> # Proposed change that would result in separate task_numbers for 
> # different characteristics within a grid
> sitecounts %>%
+     rename(site_id = MonitoringLocationIdentifier) %>% 
+     split(.$grid_id) %>%
+     purrr::map_dfr(.f = function(df){
+         
+         df_grouped <- df %>%
+             group_by(CharacteristicName) %>%
+             arrange(desc(results_count)) %>%
+             mutate(task_num_by_results = MESS::cumsumbinning(x = results_count, 
+                                                              threshold = max_results, 
+                                                              maxgroupsize = max_sites), 
+                    task_num = task_num_by_results - 1 + cur_group_id()) %>%
+             ungroup()
+     }) %>%
+     arrange(grid_id, task_num)
# A tibble: 6 x 9
  site_id   lon   lat datum grid_id CharacteristicName results_count task_num_by_results task_num
  <chr>   <dbl> <dbl> <chr> <chr>   <chr>                      <dbl>               <int>    <dbl>
1 E       -92.4  42.5 WGS84 11923   Temperature               235004                   1        1
2 B       -92.4  42.5 WGS84 11923   Temperature, water        247000                   1        2
3 D       -92.4  42.5 WGS84 11923   Temperature                15000                   2        2
4 C       -92.4  42.5 WGS84 11923   Temperature, water          7500                   2        3
5 A       -92.4  42.5 WGS84 11923   Temperature, water           151                   2        3
6 F       -92.4  42.5 WGS84 11924   Temperature                  134                   1        1
> 
```

**Comment by lekoenig** [comment]
To make this step robust to the number of tasks we need to know the maximum `task_num` for the previous group of characteristic names. Right now I can't think of a slick way to do this within a dplyr pipe, but I think this for loop is what I'm aiming for:

```r
> sitecounts %>%
+   rename(site_id = MonitoringLocationIdentifier) %>% 
+   split(.$grid_id) %>%
+   purrr::map_dfr(.f = function(df){
+      
+      df_grouped <- df %>%
+        group_by(CharacteristicName) %>%
+        arrange(desc(results_count), .by_group = TRUE) %>%
+        mutate(task_num_by_results = MESS::cumsumbinning(x = results_count, 
+                                                         threshold = max_results, 
+                                                         maxgroupsize = max_sites),
+               char_group = cur_group_id(),
+               task_num = NA_integer_) %>%
+        ungroup()
+      
+      # Each group (which represents a different characteristic name) will have
+      # task numbers that start with "1", so to create unique task numbers, we
+      # modify a new column called `task_num` that starts counting the task 
+      # numbers at the current group id. For example, both "Specific conductance" 
+      # and "Temperature" may have values for task_num_by_results of 1 and 2 but 
+      # the values of cur_group_id() (1 and 2, respectively) would mean that 
+      # they have unique values for task_num equaling 1, 2, 3, and 4.
+      for(i in seq_along(df_grouped$site_id)){
+        if(df_grouped$char_group[i] == 1){
+          df_grouped$task_num[i] <- df_grouped$task_num_by_results[i]
+        } else {
+          max_task_prev_group <- df_grouped %>%
+            filter(char_group == df_grouped$char_group[i] - 1) %>%
+            pull(task_num_by_results) %>%
+            max()
+          df_grouped$task_num[i] <- df_grouped$task_num_by_results[i] + max_task_prev_group
+        }
+      }
+      return(df_grouped)
+      
+    })
# A tibble: 6 x 10
  site_id   lon   lat datum grid_id CharacteristicName results_count task_num_by_results char_group task_num
  <chr>   <dbl> <dbl> <chr> <chr>   <chr>                      <dbl>               <int>      <int>    <int>
1 E       -92.4  42.5 WGS84 11923   Temperature               235004                   1          1        1
2 D       -92.4  42.5 WGS84 11923   Temperature                15000                   2          1        2
3 B       -92.4  42.5 WGS84 11923   Temperature, water        247000                   1          2        3
4 C       -92.4  42.5 WGS84 11923   Temperature, water          7500                   2          2        4
5 A       -92.4  42.5 WGS84 11923   Temperature, water           151                   2          2        4
6 F       -92.4  42.5 WGS84 11924   Temperature                  134                   1          1        1
>
```
