### ISSUE TITLE
Should we make this repo a "template" repository? 

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/ds-pipelines-targets-example-wqp#93]
@lindsayplatt raised the question of whether this repo would be a good candidate for a "template" repository. Pros include simple instructions for how others could use this as a base repo that they'd then customize for their own purposes. More from Lindsay:

> [The template] provides a clear, single button for getting started using the repo contents for a specific project without any risk to accidentally editing the canonical one. It requires you to pick a new repo name when you use the template so if you have multiple WQP pipelines based on this one template, you don't need to worry about Rproj naming locally

**Comment by padilla410** [comment]
I think  this should be a "yes" based on this line:

> It requires you to pick a new repo name when you use the template so if you have multiple WQP pipelines based on this one template, you don't need to worry about Rproj naming locally

**Comment by lekoenig** [comment]
Pasting some documentation from [GitHub](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) here for reference:

> Creating a repository from a template is similar to forking a repository, but there are important differences:
> 
> - A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
> - Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
> - A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

I think bullets 1 and 2 here also match our use case of having others take this repo and spin up their own projects using it as a baseline. So there seem to be some promising advantages to making the pipeline a template repo. Are there any potential downsides?

**Comment by lindsayplatt** [comment]
> can users still pull the code changes that have occurred since they first started their project

Hmmm I don't think so ... maybe they could set a remote called `base-repo` or something and `git pull base-repo` if they wanted the changes? But that is probably complex because the git histories would deviate.

**Comment by lindsayplatt** [comment]
I'm still in favor of this! I've been getting some requests from people and want to point them here, but I think this would be more useful as a template repo. I'd like to rehash this discussion.

**Comment by lekoenig** [comment]
Thanks for the nudge, @lindsayplatt! I'm generally in favor of making this repo a "template" repository. The only reason I haven't done this yet is because I think converting to a template repo will make it difficult for a user to pull any changes we make in this canonical repo after they've hit the big green "use this template" button. 

From the GH documentation:

> A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.

This means that there will be no shared history and so I expect that fetching any changes could get pretty ugly. Maybe the pros still outweigh this one con. After all, I don't plan to add much in the way of new commits and this pipeline isn't a tool or something we'll actively maintain. But we've also had limited test cases so far, and so I wouldn't be surprised if bugs or edge cases crop up as we start using this pipeline more. In that case, would folks just move forward with the code 'snapshot' that's represented in their template, or figure out how to include any changes they might want?

**Comment by padilla410** [comment]
@lekoenig lets set aside ~30 min to test this with a dummy repo on Monday.

**Comment by lekoenig** [comment]
Great point, @lindsayplatt! After thinking about this a bit more, I'm also in the template camp 🙂 

As a way to mitigate the downside of not being able to pull down new code changes, would it be helpful to document changes over time? e.g. add a changelog, use GH to create release 'versions', others?

**Comment by lindsayplatt** [comment]
I don't have a good sense of which of those to use, but I do think a way to document changes (outside of issues + PRs) is a great idea.

**Comment by lekoenig** [comment]
Now that we've decided to go with a template repo, can you also confirm that GitLab has this functionality, @padilla410? I don't see a similar option in GitLab repo settings right now.

**Comment by lekoenig** [comment]
@padilla410 verified the following:

- it is possible to migrate a "template" repo from github to gitlab
- you can make a canonical github repo a template, create some forks, and then change the canonical back to a non-template (see [EFDCr](https://github.com/padilla410/EFDCr), [EDFC-dummy](https://github.com/padilla410/EFDC-dummy), and [EFDC-dummy_2](https://github.com/padilla410/EFDC-dummy_2)) without messing things up

So I've gone ahead and made this repository a template repo and will close this issue.
